# Production configuration for Caelum Analytics
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  caelum-analytics:
    # Production optimizations
    restart: always
    
    # Production environment variables
    environment:
      - DEBUG=false
      - LOG_LEVEL=info
      - RELOAD=false
      
      # Production security - these should be set via .env file or secrets
      - SECRET_KEY=${SECRET_KEY}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - POSTGRES_URL=${POSTGRES_URL}
      - REDIS_URL=${REDIS_URL}
    
    # Production command (no reload)
    command: ["uv", "run", "uvicorn", "caelum_analytics.web.app:app", "--host", "0.0.0.0", "--port", "8090", "--workers", "4"]
    
    # Enhanced health checks for production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

  redis:
    restart: always
    
    # Production Redis configuration
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  influxdb:
    restart: always
    
    environment:
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  postgres:
    restart: always
    
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
    # Production PostgreSQL tuning
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
    
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 256M
    
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

# Production-specific networks with better isolation
networks:
  default:
    name: caelum-analytics-prod
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16